#!/bin/bash

set -eux

KEYBALL_DIR="${KEYBALL_DIR:-../keyball/qmk_firmware/keyboards/keyball}"

echo $KEYBALL_DIR

if [ ! -d "$KEYBALL_DIR" ] ; then
  echo "Not found keyball directory: $KEYBALL_DIR"
  exit 1
fi

cp -Rp "$KEYBALL_DIR" keyboards/

find keyboards/keyball -type f -name .noci | xargs -r rm

if which dos2unix > /dev/null 2>&1 ; then
  find keyboards/keyball -type f -regex '.*\.\(c\|h\|json\|md\)' | xargs -r dos2unix -q
fi
