#!/bin/bash
#
# Flash the ATmega32U4 firmware (HEX file) via DFU
#
# USAGE: flash-dfu {HEX file}

set -eu

if ! command -v dfu-programmer >/dev/null 2>&1; then
  echo "Error: dfu-programmer is not installed." >&2
  exit 1
fi

if [[ $# -lt 1 ]]; then
  echo "USAGE: $0 {HEX file}" >&2
  exit 1
fi

HEX_FILE=$1 ; shift
if [[ ! -r "$HEX_FILE" ]]; then
  echo "can't read $HEX_FILE"
  exit 1
fi

TARGET=atmega32u4

echo "Waiting DFU device connection..."
while ! dfu-programmer "$TARGET" get bootloader-version >/dev/null 2>&1; do
  sleep 0.5
done

dfu-programmer "$TARGET" erase --force
dfu-programmer "$TARGET" flash "$HEX_FILE"
dfu-programmer "$TARGET" reset
